const ERROR_CODES = {
  0: '¡Discúlpanos por el inconveniente! Solucionaremos el problema en un momento.',
  100: 'Ocurrió un error al comunicarnos con el banco. Cód. error: 100',
  200: 'El banco ha regresado un error que no permitió procesar el pago.',
  201: 'Ocurrió un error general en el sistema de Visa o Master Card, espera unos momentos para reintentar la transacción',
  421: 'El servicio 3D Secure no está disponible, espera unos momentos para reintentar la transacción.',
  422: 'Ocurrió un problema genérico al momento de realizar la transacción, inténtalo en otro momento.',
  423: 'La autenticación no fue exitosa, el comprador no se pudo autenticar con éxito.',
  424: 'Autenticación 3D Secure no fue completada. Cód. error: 424',
  425: 'Autenticación inválida. No has ingresado correctamente la contraseña 3D Secure.',
  430: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 430',
  431: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 431',
  432: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 432',
  433: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 433',
  434: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 434',
  435: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 435',
  436: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 436',
  437: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 437',
  438: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 438',
  439: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 439',
  440: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 440',
  441: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 441',
  442: 'Ocurrió un error de parte nuestra, estamos trabajando para solucionarlo. Cód. error: 442',
  443: 'La pasarela de pagos solo acepta tarjetas VISA o Master Card, si has ingresado bien tu tarjeta comunícate con nosotros.',
  444: 'La pasarela de pagos solo acepta tarjetas VISA o Master Card, si has ingresado bien tu tarjeta comunícate con nosotros.',
};

export default ERROR_CODES;
