#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "post-merge"

changed() {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

if changed 'yarn.lock'; then
  echo "📦 yarn.lock changed. Run npm install to bring your dependencies up to date."
fi
